site_name: RetroShare
site_url: https://retroshare.readthedocs.io
site_description: RetroShare User Guide
site_author: RetroShare Community

repo_url: https://github.com/retroshare/documentation.git

pages:
- Home: index.md
- User Guide: 
    - Installation: user-guide/installation.md
    - First Steps: user-guide/first-steps.md
    - Settings: user-guide/settings.md
    - Interface: user-guide/interface.md
- Developer Section:
    - Compilation: developer/compilation.md
- About: 
    - About: about/about.md
    - License: about/license.md
    - Contributing: about/contributing.md

copyright: CC-BY-SA 4.0
theme: readthedocs

extra:
  author:
    github: 'RetroShare'
    twitter: 'RetroShare'

markdown_extensions:
    - toc:
permalink: 
