site_name: RetroShare
site_url: https://retroshare.readthedocs.io
site_description: RetroShare User Guide
site_author: RetroShare Community

repo_url: https://github.com/retroshare/documentation.git

site_favicon: favicon.ico

pages:
- Home: index.md
- User Guide: 
    - Installation: user-guide/installation.md
    - First Steps: user-guide/first-steps.md
    - Settings: user-guide/settings.md
    - Interface: user-guide/interface.md
    - Plugins: user-guide/plugins.md
    - rscollection: user-guide/rscollection.md
- Tutorial: 
    - Location Creation: tutorial/location.md  
    - Tor Hidden Node: tutorial/tor-hidden-rs-node.md  
    - I2P Hidden Node: tutorial/i2p-hidden-rs-node.md  
- Developer Section:
    - Compilation: developer/compilation.md
    - Coding: developer/coding.md
- Concept:
    - Topology: concept/topology.md 
- About: 
    - About: about/about.md
    - History: about/history.md
    - License: about/license.md
    - Contributing: about/contributing.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by the RetroShare Community
theme: readthedocs


markdown_extensions:
    - toc:
        permalink: 
