site_name: RetroShare
site_url: https://retroshare.readthedocs.io
site_description: RetroShare User Guide
site_author: RetroShare Community

repo_url: https://github.com/retroshare/documentation.git

pages:
- Home: index.md
- User Guide: 
    - Installation: user-guide/installation.md
    - First Steps: user-guide/first-steps.md
- Settings:
    - General: settings/general.md
    - Network: settings/network.md    
- About: 
    - About: about/about.md
    - License: about/license.md
    - Contributing: about/contributing.md

theme: readthedocs
